version: "3"
services:
  frontend:
    build:
      context: ./frontend
      args:
        - MODE=${MODE}
        - SERVER_NAME=${SERVER_NAME}
    volumes:
      - html_volume:/app/dist

  backend:
    build: ./backend
    depends_on:
      - mongo
    volumes:
      - files_volume:/files
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}

  mongo:
    image: mongo:latest
    volumes:
      - mongo_volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"

  nginx:
    build:
      context: ./nginx
      args:
        - MODE=${MODE}
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SERVER_NAME=$SERVER_NAME
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
      - html_volume:/usr/share/nginx/html:ro
    restart: always
    depends_on:
      - frontend

  bot:
    build:
      context: ./bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - MODE=${MODE}
      - SERVER_NAME=${SERVER_NAME}

volumes:
  mongo_volume:
  files_volume:
  html_volume:
