version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
      build: ./backend
      ports:
        - "8000:8000"
      depends_on:
        - mongo
      volumes:
        - files_volume:/files

  mongo:
    image: mongo:latest
    volumes:
      - mongo_volume:/data/db


volumes:
  mongo_volume:
  files_volume:
