files: 'backend\/.*'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.5.0'
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: '24.2.0'
    hooks:
    -   id: black
        args: [ --check, ./backend ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0'
    hooks:
    -   id: mypy

-   repo: https://github.com/PyCQA/flake8
    rev: '7.0.0'
    hooks:
    -   id: flake8
        entry: flake8p
        additional_dependencies: [Flake8-pyproject]
        args: [ --toml-config, ./backend/pyproject.toml, .]
-   repo: https://github.com/PyCQA/isort
    rev: '5.13.2'
    hooks:
    -   id: isort
        args: [ --check, ./backend ]
