name: Backend

run-name: ${{ github.event_name }} to ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    paths:
      - backend/**
  pull_request:
    paths:
      - backend/**

env:
  path: ./backend

jobs:
  linting_black:
    name: Linting with black (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install black
        run: pip install black

      - name: Run black
        run: black --check --verbose --diff --color ${{ env.path }}

  linting_flake:
    name: Linting with flake8 (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install flake8 with plugins
        run: pip install flake8 flake8-bugbear

      - name: Flake8 linting
        run: |
          flake8 --statistics --show-source --max-line-length 88  ${{ env.path }}

  typing_mypy:
    name: Checking static types with mypy (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install mypy
        run: pip install mypy

      - name: Creating configuration file
        run: |
          echo '[mypy]' >> ${{ env.path }}/mypy.ini
          echo 'plugins = pydantic.mypy' >> ${{ env.path }}/mypy.ini

      - name: Mypy checking
        run: |
          cd ${{ env.path }}
          mypy --install-types .

  testing:
    name: Testing ${{ matrix.python-version }}
    needs: [linting_black, linting_flake, typing_mypy]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Get full code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install --no-cache-dir --upgrade -r ${{ env.path }}/requirements.txt pytest mongomock setuptools

      - name: Run tests
        run: |
          cd ${{ env.path }}
          pytest .
