name: Run frontend tests

run-name: ${{ github.event_name }} to ${{ github.ref_name }} by @${{ github.actor }}

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - main

jobs:
  linting:
    name: Linting
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/react_linting.yml

  testing:
    name: Testing
    needs: [ linting ]
    if: ${{ !failure() && !cancelled() && always() }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18.x', '20.x' ]
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
#          cache: 'npm'

      - name: Get full code
        uses: actions/checkout@v4
